id: 115cc74d006040c8849d63c3a1e3b61d
initial_creation_type: ocr
source_metadata:
  volumes:
    e31ecbc175434613b008e9ee3b6dd224:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: དབུ་མའི་མན་ངག།
      total_pages: 1902
      volume_number: 64
